//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManager.Properties.ar_iq {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventoryManager.Properties.ar_iq.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير المخزن.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العرض.
        /// </summary>
        public static string GiveAwayName {
            get {
                return ResourceManager.GetString("GiveAwayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عروض.
        /// </summary>
        public static string GiveAwayPageTitle {
            get {
                return ResourceManager.GetString("GiveAwayPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        public static string InventoryPageAddLabel {
            get {
                return ResourceManager.GetString("InventoryPageAddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هدية.
        /// </summary>
        public static string InventoryPageGiftLabel {
            get {
                return ResourceManager.GetString("InventoryPageGiftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هداية.
        /// </summary>
        public static string InventoryPageGivenAwayLabel {
            get {
                return ResourceManager.GetString("InventoryPageGivenAwayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خارج المركز.
        /// </summary>
        public static string InventoryPageOutsideLabel {
            get {
                return ResourceManager.GetString("InventoryPageOutsideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقيقي.
        /// </summary>
        public static string InventoryPageRealLabel {
            get {
                return ResourceManager.GetString("InventoryPageRealLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string InventoryPageRemoveLabel {
            get {
                return ResourceManager.GetString("InventoryPageRemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الناتج.
        /// </summary>
        public static string InventoryPageResultLabel {
            get {
                return ResourceManager.GetString("InventoryPageResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string InventoryPageSendLabel {
            get {
                return ResourceManager.GetString("InventoryPageSendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سستم.
        /// </summary>
        public static string InventoryPageSystemLabel {
            get {
                return ResourceManager.GetString("InventoryPageSystemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخزن.
        /// </summary>
        public static string InventoryPageTitle {
            get {
                return ResourceManager.GetString("InventoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف الكل.
        /// </summary>
        public static string MainPageDeleteAll {
            get {
                return ResourceManager.GetString("MainPageDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصدير اكسل.
        /// </summary>
        public static string MainPageExportAsExcel {
            get {
                return ResourceManager.GetString("MainPageExportAsExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هداية.
        /// </summary>
        public static string MainPageGiftsLabel {
            get {
                return ResourceManager.GetString("MainPageGiftsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خارج المركز.
        /// </summary>
        public static string MainPageOutsideLabel {
            get {
                return ResourceManager.GetString("MainPageOutsideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتجات.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث القائمة.
        /// </summary>
        public static string MainPageUpdateList {
            get {
                return ResourceManager.GetString("MainPageUpdateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر قديم.
        /// </summary>
        public static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خارج المركز.
        /// </summary>
        public static string SentOutsidePageTitle {
            get {
                return ResourceManager.GetString("SentOutsidePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع المبيعات.
        /// </summary>
        public static string SentOutsideTotalSold {
            get {
                return ResourceManager.GetString("SentOutsideTotalSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا البرنامج عبارة عن تسهيل شغل الجردات, صنع من قبل زانا مسعود.
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حول هذا البرنامج.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخ احتيطي.
        /// </summary>
        public static string SettingsPageDatabaseBackup {
            get {
                return ResourceManager.GetString("SettingsPageDatabaseBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف جميع البيانات.
        /// </summary>
        public static string SettingsPageDatabaseDeleteAll {
            get {
                return ResourceManager.GetString("SettingsPageDatabaseDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استرجاع النسخة الاحتيطية.
        /// </summary>
        public static string SettingsPageDatabaseRestore {
            get {
                return ResourceManager.GetString("SettingsPageDatabaseRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قاعدة البيانات.
        /// </summary>
        public static string SettingsPageDatabaseTitle {
            get {
                return ResourceManager.GetString("SettingsPageDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصيص.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الخصوصية.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غامق.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتح.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افتراضي.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخادم.
        /// </summary>
        public static string SettingsPageServerTitle {
            get {
                return ResourceManager.GetString("SettingsPageServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعدادات.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجوع.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فتح او غلق.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتجات.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعدادات.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخزن السستم.
        /// </summary>
        public static string ShellSystemInventoryPage {
            get {
                return ResourceManager.GetString("ShellSystemInventoryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المركز.
        /// </summary>
        public static string SystemInventoryAgentLabel {
            get {
                return ResourceManager.GetString("SystemInventoryAgentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ.
        /// </summary>
        public static string SystemInventoryDateLabel {
            get {
                return ResourceManager.GetString("SystemInventoryDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...جاب البيانات.
        /// </summary>
        public static string SystemInventoryFetchData {
            get {
                return ResourceManager.GetString("SystemInventoryFetchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر تحديث.
        /// </summary>
        public static string SystemInventoryLastUpdate {
            get {
                return ResourceManager.GetString("SystemInventoryLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث.
        /// </summary>
        public static string SystemInventoryUpdateLabel {
            get {
                return ResourceManager.GetString("SystemInventoryUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموع.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
