//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventoryManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventoryManager.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/zana_mziry_.
        /// </summary>
        public static string ContactMeInstagramUrl {
            get {
                return ResourceManager.GetString("ContactMeInstagramUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZANA_MZIRY_.
        /// </summary>
        public static string ContactMeInstagramUsername {
            get {
                return ResourceManager.GetString("ContactMeInstagramUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0750 386 4007.
        /// </summary>
        public static string ContactMePhone {
            get {
                return ResourceManager.GetString("ContactMePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Me.
        /// </summary>
        public static string ContactMeTitle {
            get {
                return ResourceManager.GetString("ContactMeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://zanamziry.github.io.
        /// </summary>
        public static string ContactMeWebsite {
            get {
                return ResourceManager.GetString("ContactMeWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://web.whatsapp.com/send/?phone=9647503864007&amp;text&amp;type=phone_number&amp;app_absent=0.
        /// </summary>
        public static string ContactMeWhatsAppUrl {
            get {
                return ResourceManager.GetString("ContactMeWhatsAppUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Batch.
        /// </summary>
        public static string DialogsAddBatch {
            get {
                return ResourceManager.GetString("DialogsAddBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present a Gift.
        /// </summary>
        public static string DialogsGiveaway {
            get {
                return ResourceManager.GetString("DialogsGiveaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Product.
        /// </summary>
        public static string DialogsSendProduct {
            get {
                return ResourceManager.GetString("DialogsSendProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifts Quantity.
        /// </summary>
        public static string GiveAwayAmountGiven {
            get {
                return ResourceManager.GetString("GiveAwayAmountGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        public static string GiveawayDate {
            get {
                return ResourceManager.GetString("GiveawayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        public static string GiveAwayName {
            get {
                return ResourceManager.GetString("GiveAwayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifts.
        /// </summary>
        public static string GiveAwayPageTitle {
            get {
                return ResourceManager.GetString("GiveAwayPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string InventoryPageAddLabel {
            get {
                return ResourceManager.GetString("InventoryPageAddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire.
        /// </summary>
        public static string InventoryPageExpire {
            get {
                return ResourceManager.GetString("InventoryPageExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift.
        /// </summary>
        public static string InventoryPageGiftLabel {
            get {
                return ResourceManager.GetString("InventoryPageGiftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifts.
        /// </summary>
        public static string InventoryPageGivenAwayLabel {
            get {
                return ResourceManager.GetString("InventoryPageGivenAwayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string InventoryPageInventoryHeader {
            get {
                return ResourceManager.GetString("InventoryPageInventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string InventoryPageNext {
            get {
                return ResourceManager.GetString("InventoryPageNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string InventoryPageNote {
            get {
                return ResourceManager.GetString("InventoryPageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string InventoryPageOpen {
            get {
                return ResourceManager.GetString("InventoryPageOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside.
        /// </summary>
        public static string InventoryPageOutsideLabel {
            get {
                return ResourceManager.GetString("InventoryPageOutsideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string InventoryPagePrevious {
            get {
                return ResourceManager.GetString("InventoryPagePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real.
        /// </summary>
        public static string InventoryPageRealLabel {
            get {
                return ResourceManager.GetString("InventoryPageRealLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string InventoryPageRemoveLabel {
            get {
                return ResourceManager.GetString("InventoryPageRemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string InventoryPageResultLabel {
            get {
                return ResourceManager.GetString("InventoryPageResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string InventoryPageSendLabel {
            get {
                return ResourceManager.GetString("InventoryPageSendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string InventoryPageSystemLabel {
            get {
                return ResourceManager.GetString("InventoryPageSystemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string InventoryPageTitle {
            get {
                return ResourceManager.GetString("InventoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string InventoryPageTotal {
            get {
                return ResourceManager.GetString("InventoryPageTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string MainPageDeleteAll {
            get {
                return ResourceManager.GetString("MainPageDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire.
        /// </summary>
        public static string MainPageExpireTitle {
            get {
                return ResourceManager.GetString("MainPageExpireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As Excel.
        /// </summary>
        public static string MainPageExportAsExcel {
            get {
                return ResourceManager.GetString("MainPageExportAsExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifts.
        /// </summary>
        public static string MainPageGiftsLabel {
            get {
                return ResourceManager.GetString("MainPageGiftsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifts.
        /// </summary>
        public static string MainPageGiveawayTitle {
            get {
                return ResourceManager.GetString("MainPageGiveawayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string MainPageLocalTitle {
            get {
                return ResourceManager.GetString("MainPageLocalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside.
        /// </summary>
        public static string MainPageOutsideLabel {
            get {
                return ResourceManager.GetString("MainPageOutsideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside.
        /// </summary>
        public static string MainPageOutsideTitle {
            get {
                return ResourceManager.GetString("MainPageOutsideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string MainPageResultTitle {
            get {
                return ResourceManager.GetString("MainPageResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string MainPageSystemTitle {
            get {
                return ResourceManager.GetString("MainPageSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update List.
        /// </summary>
        public static string MainPageUpdateList {
            get {
                return ResourceManager.GetString("MainPageUpdateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Price.
        /// </summary>
        public static string ProductOld {
            get {
                return ResourceManager.GetString("ProductOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product PV.
        /// </summary>
        public static string ProductPV {
            get {
                return ResourceManager.GetString("ProductPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining .
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application needs a restart to change the language.
        /// </summary>
        public static string RestartNeeded {
            get {
                return ResourceManager.GetString("RestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Quantity.
        /// </summary>
        public static string SentOutsideAmountSent {
            get {
                return ResourceManager.GetString("SentOutsideAmountSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold Quantity.
        /// </summary>
        public static string SentOutsideAmountSold {
            get {
                return ResourceManager.GetString("SentOutsideAmountSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string SentOutsideLocation {
            get {
                return ResourceManager.GetString("SentOutsideLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Outside.
        /// </summary>
        public static string SentOutsidePageTitle {
            get {
                return ResourceManager.GetString("SentOutsidePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total PV.
        /// </summary>
        public static string SentOutsideTotalPoints {
            get {
                return ResourceManager.GetString("SentOutsideTotalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sold.
        /// </summary>
        public static string SentOutsideTotalSold {
            get {
                return ResourceManager.GetString("SentOutsideTotalSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://zanamziry.pythonanywhere.com.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string SettingsCheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is made by Zana Masoud to help make managing inventories easier.
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About This Application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string SettingsPageDatabaseBackup {
            get {
                return ResourceManager.GetString("SettingsPageDatabaseBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string SettingsPageDatabaseDeleteAll {
            get {
                return ResourceManager.GetString("SettingsPageDatabaseDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string SettingsPageDatabaseRestore {
            get {
                return ResourceManager.GetString("SettingsPageDatabaseRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string SettingsPageDatabaseTitle {
            get {
                return ResourceManager.GetString("SettingsPageDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Test.
        /// </summary>
        public static string SettingsPageLoginTest {
            get {
                return ResourceManager.GetString("SettingsPageLoginTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string SettingsPageLoginTestFailed {
            get {
                return ResourceManager.GetString("SettingsPageLoginTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful.
        /// </summary>
        public static string SettingsPageLoginTestSuccess {
            get {
                return ResourceManager.GetString("SettingsPageLoginTestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string SettingsPageLoginTestTitle {
            get {
                return ResourceManager.GetString("SettingsPageLoginTestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Credentials.
        /// </summary>
        public static string SettingsPageLoginTitle {
            get {
                return ResourceManager.GetString("SettingsPageLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SettingsPagePassword {
            get {
                return ResourceManager.GetString("SettingsPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string SettingsPageServerTitle {
            get {
                return ResourceManager.GetString("SettingsPageServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SettingsPageUsername {
            get {
                return ResourceManager.GetString("SettingsPageUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Inventory.
        /// </summary>
        public static string ShellSystemInventoryPage {
            get {
                return ResourceManager.GetString("ShellSystemInventoryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Balance.
        /// </summary>
        public static string SystemInventoryCloseBalance {
            get {
                return ResourceManager.GetString("SystemInventoryCloseBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string SystemInventoryDateLabel {
            get {
                return ResourceManager.GetString("SystemInventoryDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Data....
        /// </summary>
        public static string SystemInventoryFetchData {
            get {
                return ResourceManager.GetString("SystemInventoryFetchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string SystemInventoryLastUpdate {
            get {
                return ResourceManager.GetString("SystemInventoryLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Balance.
        /// </summary>
        public static string SystemInventoryOpenBalance {
            get {
                return ResourceManager.GetString("SystemInventoryOpenBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Center.
        /// </summary>
        public static string SystemInventoryServiceCenterLabel {
            get {
                return ResourceManager.GetString("SystemInventoryServiceCenterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold Quantity.
        /// </summary>
        public static string SystemInventorySoldQuantity {
            get {
                return ResourceManager.GetString("SystemInventorySoldQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string SystemInventoryUpdateLabel {
            get {
                return ResourceManager.GetString("SystemInventoryUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Update Is Available Do You Want To Update To.
        /// </summary>
        public static string UpdateServiceNewUpdate {
            get {
                return ResourceManager.GetString("UpdateServiceNewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Availbable!.
        /// </summary>
        public static string UpdateServiceNewUpdateTitle {
            get {
                return ResourceManager.GetString("UpdateServiceNewUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Update Found.
        /// </summary>
        public static string UpdateServiceNoUpdateFound {
            get {
                return ResourceManager.GetString("UpdateServiceNoUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem while searching for updates.
        /// </summary>
        public static string UpdateServiceProblemOccurred {
            get {
                return ResourceManager.GetString("UpdateServiceProblemOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required For the Update To Take Effect.
        /// </summary>
        public static string UpdateServiceRestartRequired {
            get {
                return ResourceManager.GetString("UpdateServiceRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the latest version.
        /// </summary>
        public static string UpdateServiceThisIsTheLatest {
            get {
                return ResourceManager.GetString("UpdateServiceThisIsTheLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Complete.
        /// </summary>
        public static string UpdateServiceUpdateComplete {
            get {
                return ResourceManager.GetString("UpdateServiceUpdateComplete", resourceCulture);
            }
        }
    }
}
